services:

  orders-db:
    image: postgres:16.2
    container_name: orders_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders_db
    ports:
      - '${ORDERS_DB_PORT}:${ORDERS_DB_PORT}'
    volumes:
      - ./orders-ms/postgres:/var/lib/postgresql/data

  nats-server:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"

  client-gateway:
    build: ./client-gateway
    ports:
      - "${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}"
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222

  products-ms:
    build: ./products-ms
    ports:
      - "${PRODUCTS_PORT}:${PRODUCTS_PORT}"
    volumes:
      - ./products-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${PRODUCTS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  orders-ms:
    depends_on:
      - orders-db
    build: ./orders-ms
    ports:
      - "${ORDERS_PORT}:${ORDERS_PORT}"
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${ORDERS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=postgresql://user:password@orders-db:${ORDERS_DB_PORT}/orders_db?schema=public

  payments-ms:
    build: ./payments-ms
    ports:
      - "${PAYMENTS_PORT}:${PAYMENTS_PORT}"
    volumes:
      - ./payments-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${PAYMENTS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - SUCCESS_URL=${SUCCESS_URL}
      - CANCEL_URL=${CANCEL_URL}

  auth-ms:
    build: ./auth-ms
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    volumes:
      - ./auth-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${AUTH_PORT}
      - NATS_SERVERS=nats://nats-server:4222
